name: 'POST API Call Action'
description: 'Send a POST request'
author: 'Derek Kershner'
branding:
  icon: 'phone'  
  color: 'orange'
inputs:
  url:
    description: 'URL to send post request to'
    required: true
  data:
    description: 'JSON string of data to pass into request'
    default: '{}'
    required: false
  headers:
    description: 'JSON string of headers to pass into request'
    default: '{}'
    required: false
  params:
    description: 'JSON string of query parameters to pass into request'
    default: '{}'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'